#!/bin/sh

# pre-trained file location:
pre_trained_file_url="http://data.csail.mit.edu/tofu/dataset/vimeo_triplet.zip"

# if axel exists - run with axel

# if wget exists - run with wget

# if file exists - untar

# delete source